package com.solegendary.reignofnether.sounds;

public enum SoundAction {
    USE_PORTAL,
    RANDOM_CAVE_AMBIENCE,
    ALLY,
    CHAT,
    ENEMY,
    BELL,
    BEACON_ACTIVATE,
    BEACON_DEACTIVATE,
    LEVEL_UP,
    BLOODLUST,
    HEROISM,
    WRETCHED_WRAITH_ATTACK_QUIET,
    WRETCHED_WRAITH_ATTACK_LOUD,
    WRETCHED_WRAITH_TELEPORT_START,
    WRETCHED_WRAITH_TELEPORT_END
}
